os: windows      # Windows Server, version 1803
language: shell  # 'language: python' is not yet supported on Windows

env:
  global:
    - PY38PATH=/c/Python38:/c/Python38/Scripts
  
matrix:
  include:
    - name: "Py3: Run tests"
      env: PATH=$PY38PATH:$PATH
      before_install:
        - choco install python

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install git+https://github.com/wbnk/pytube
  - pip install pyinstaller
script:
  - pyinstaller --onefile --noconsole --name ytdl-helper main.py
  - sleep 1
  - ls -l dist
  - echo "File size should indicate whether it was successful or not!"
  

  

