# https://blog.travis-ci.com/2018-10-11-windows-early-release
# https://docs.travis-ci.com/user/reference/windows
# https://chocolatey.org/packages/python
# https://www.pyinstaller.org
# https://travis-ci.community/t/pyinstaller-can-build-and-run-a-windows-exe-but-no-console-output-is-visible/2767
os: windows      # Windows Server, version 1803
language: shell  # 'language: python' is not yet supported on Windows

env:
  global:
    - PY37PATH=/c/Python38:/c/Python38/Scripts
  
matrix:
  include:
    - name: "Py3: Run tests"
      env: PATH=$PY37PATH:$PATH
      before_install:
        - choco install python

install:
  - python -m pip install --upgrade pip
  #- pip install -r requirements.txt
  - pip install pyinstaller
  - pip install youtube_dl

script:
  - pyinstaller --onefile --noconsole --name mp3_gui main.py
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - echo "Build appears to be finished!"
  
deploy:
  provider: releases
  api_key:
    secure: "ABgSVzk94FrMjeoGeVrtzbRam/iXsAH/NSdDqNzPHqf/kpuqnJ7gYNV6OoRB5Mrqpcm9cVsKTnexYQgnbtlCJ25La27/IPoVKkiu/CBGTdXTv59gHSTaqdv+hUP2Hk0ShSjFpkYIPGf0pB29WFT3bYXeMk3M7EDr5VCvw65O0Q4oMQ42DnIymAxWSRigp8prsNNDbw0+S5CfEYXv9JiZvdiUad2oXT3WCWa6CPczrfwpB0osRsXprEGp6naTXuZxKSxwzIv3WuXYW7hMADXYolpFgiZEreT+aSHPrXP08asLkGgLf3SdASQGoWUr2mNn/a4gKDW3kKaagFCNHjd4HytzpTHCr3kIXW3xeFaFaopbeW7ynxr0mmRoxSvWtVegWxBujYXeDFk8p7zfykRZ7Ud48jIcuHIDRPI6y/Ga9eQfCrrf1yOi8ddvlF/quO3VxV0FQFzgyKlIHG3a/cLSJE+QY6L64cnBlKhjYvVdnPkqyo7rRQ7ZXie6W3VfwBCVVT+bjNmkfwf5KbtClA4czbL5wogevSjanZaWrMNZ9LdkdJy4P7KWPtNSfpg/42W8IsZom9q0NYoR6hbrhbpvWV0+PClAm4LO7Nk2zW4FHhnP9QUbDxzgePEfDtHARaAXcPOA0DCHRchskr8GSjtciDHE8l3DRbvblu71Zyog9MA="
  file: "mp3_gui.exe"
  cleanup: false
  on:
    tags: false
